config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root 'reports#index'
  resources :reports
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :merchant

  validates :name, :price, presence: :true
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  belongs_to :user

  validates :name, presence: :true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :purchaser
  belongs_to :item
  belongs_to :user
  belongs_to :report

  validates :count, presence: :true
end

app/models/purchaser.rb
class Purchaser < ApplicationRecord
  belongs_to :user

  validates :name, presence: :true
end

app/models/report.rb
require 'csv'

class Report < ApplicationRecord
  include AASM

  has_one_attached :file
  belongs_to :user
  has_many :purchases, dependent: :destroy

  validates :name, presence: true
  validates_each :file, on: :create do |record, attr, value|
    record.errors.add(attr, :blank) unless value.attached?
    record.errors.add(attr, :invalid) unless valid_report?(value)
  end
  validates_each :file do |record, attr, value|
    if !record.new_record? && record.send(:new_file?)
      record.errors.add(attr, :invalid, message: 'should be blank')
    end
  end

  after_commit :broadcast_creation, on: :create
  after_commit :process_file_in_background, if: :new_file?, on: :create
  after_commit -> { user.calculate_income! }, if: -> { saved_change_to_income? || destroyed? }

  aasm do
    state :enqueued, initial: true
    state :done

    event :process, before: :process_file! do
      transitions to: :done
    end
  end

  def self.valid_report?(report_file)
    return true unless report_file.attached?
    csv = buid_csv(report_file)

    valid_headers = ["purchaser name", "item description", "item price",
      "purchase count", "merchant address", "merchant name"]

    return valid_headers.sort == csv.headers.sort
  end

  def self.buid_csv(file)
    path = ActiveStorage::Blob.service.send(:path_for, file.key)
    CSV.read(path, headers: true, col_sep: "\t")
  end

  private

  def new_file?
    file.attached? && file.saved_change_to_blob_id?
  end

  def process_file_in_background
    ProcessReportJob.perform_later(self)
  end

  def broadcast_creation
    ActionCable.server.broadcast 'report_notifications_channel',
      report: ViewHelper.render(self)
  end

  def clean_purchases!
    purchases.destroy_all
  end

  def process_file!
    csv = self.class.buid_csv(file)
    self.income = 0

    csv.each do |row|
      merchant = user.merchants.find_or_create_by(name: row['merchant name']) do |merchant|
        merchant.address = row['merchant address']
      end

      purchaser = user.purchasers.find_or_create_by(name: row['purchaser name'])

      item = user.items.find_or_create_by(name: row['item description'], merchant: merchant) do |item|
        item.price = row['item price'].to_f
      end

      purchase = user.purchases.find_or_create_by(report: self, purchaser: purchaser, item: item) do |purchase|
        purchase.count = row['purchase count'].to_i
      end

      self.income += purchase.count * item.price
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_many :reports
  has_many :purchasers
  has_many :purchases
  has_many :merchants
  has_many :items

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def calculate_income!
    self.income = reports.done.reduce(0) { |total, r| total + r.income }
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user
    else
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/concerns/pagination.rb
module Pagination
  extend ActiveSupport::Concern

  private

  def paginate(resources)
    resources = resources.
      page(pagination_params[:page]).
      per(pagination_params[:per_page])

    @more_link = build_pagination_link(resources)

    resources
  end

  def pagination_params
    params.permit(:page, :per_page)
  end

  def build_pagination_link(resources)
    total_pages = resources.total_pages
    current_page = resources.current_page
    return if current_page == total_pages

    pagination_param = { page: current_page + 1, per_page: pagination_params[:per_page] }.to_param
    request.path + '?' + pagination_param
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include Pagination
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  def index
    @reports = paginate(current_user.reports.includes(file_attachment: :blob).
      order(created_at: :desc))
  end

  # GET /reports/1
  def show
    @csv = Report.buid_csv(@report.file)
  end

  # GET /reports/new
  def new
    @report = current_user.reports.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  def create
    @report = current_user.reports.new(create_params)

    if @report.save
      redirect_to @report, notice: 'Report was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /reports/1
  def update
    if @report.update(update_params)
      redirect_to @report, notice: 'Report was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /reports/1
  def destroy
    @report.destroy
    redirect_to reports_url, notice: 'Report was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = current_user.reports.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def create_params
    params.require(:report).permit(:name, :file)
  end

  def update_params
    params.require(:report).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-warning"
    end
  end

  def html_report_state(report)
    icon =
      case report.aasm_state
      when 'enqueued' then 'clock-o'
      when 'done' then 'check-circle'
      end


    tag.i class: "fa fa-#{icon} fa-fw", data: { toggle: 'tooltip' },
      title: report.aasm_state.humanize
  end

  def html_report_income(report)
    return '-' unless report.done?
    number_to_currency(report.income)
  end

  def shoud_show_back?
    ![root_path, reports_path].include?(request.path) && !devise_controller?
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container d-flex justify-content-between">
    <a class="navbar-brand d-flex align-items-center" href="/">FoobarImporter</a>

    <% if current_user %>
      <ul class="navbar-nav my-9 my-md-0">
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown06" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "Welcome! #{current_user.email}" %>
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdown06">
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item') %>
          </div>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoobarImporter</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100">
    <header>
      <%= render 'layouts/navbar' %>
    </header>

    <main role="main" class="flex-shrink-0">
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %> text-center">
          <%= value %>
        </div>
      <% end %>
      <div class="container">
        <%= link_to('Back', :back, class: 'btn btn-secondary') if shoud_show_back? %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/reports/_form.html.erb
<div class="container">
  <%= form_with(model: report, local: true) do |form| %>
    <% if report.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

        <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.text_field :name, class: 'form-control', placeholder: 'Name' %>
    </div>

    <% if action_name == 'new' %>
      <div class="field">
        <%= form.label :file %>
        <%= form.file_field :file, class: 'form-control-file' %>
      </div>
    <% end %>

    <div class="actions">
      <%= form.submit(class: 'btn btn-lg btn-primary btn-block') %>
    </div>
  <% end %>
</div>

app/views/reports/_report.html.erb
<tr id="report-<%= report.id %>" class="report">
  <td><%= link_to report.name, report_path(report) %></td>
  <td><%= report.file.blob.filename %></td>
  <td class="status"><%= html_report_state(report) %></td>
  <td class="income"><%= html_report_income(report) %></td>
  <td>
    <%= link_to 'Download', url_for(report.file) %>
    <%= link_to 'Edit', edit_report_path(report) %>
    <%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/reports/edit.html.erb
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Edit Report</h1>
</div>

<%= render 'form', report: @report %>

app/views/reports/index.html.erb
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <% if @reports.present? %>
    <h1 class="display-4">Income</h1>
    <p class="lead">
      <span id="total-income"><%= number_to_currency current_user.income %><span>
    </p>
  <% else %>
    <h1 class="display-4">You still don't have reports!</h1>
  <% end %>

  <%= link_to 'New Report', new_report_path, class: 'btn btn-primary my-2' %>
</div>

<div class="container text-center">
  <% if @reports.present? %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">File name</th>
          <th scope="col">Status</th>
          <th scope="col">Income</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>

      <tbody id="reports" class="js-reports">
        <%= render @reports %>
      </tbody>
    </table>

    <% if @more_link %>
      <%= link_to @more_link, id: 'js-more-reports', class: 'btn btn-outline-primary', remote: true do %>
        Load more
      <% end %>
    <% end %>
  <% end %>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="https://getbootstrap.com/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">© 2017-2019</small>
      </div>
    </div>
  </footer>
</div>

app/views/reports/index.js.erb
<% if @more_link %>
  $('#js-more-reports').attr('href', '<%= @more_link %>');
<% else %>
  $('#js-more-reports').remove();
<% end %>

$('#reports.js-reports').append('<%= j render(@reports) %>');

app/views/reports/new.html.erb
<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">New Report</h1>
</div>

<%= render 'form', report: @report %>

app/views/reports/show.html.erb
<div id="report-<%= @report.id %>" class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4"><%= @report.name %></h1>

  <p class="lead">
    <span class="income">
      <% if @report.done? %>
        <%= number_to_currency @report.income %>
      <% else %>
        Your report is still processing...
      <% end %>
    <span>
  </p>

  <%= link_to 'Edit', edit_report_path(@report), class: 'btn btn-primary my-2' %>
</div>

<div class="container">
  <table class="table table-sm">
    <thead>
      <tr>
        <% @csv.headers.each do |header| %>
          <th scope="col"><%= header %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @csv.each do |row| %>
        <tr>
          <% @csv.headers.each do |header| %>
            <td><%= row[header] %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>